name: flutter_opencv_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  # Dart FFI requires 2.6.0
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  native_opencv:
    path: native_opencv
  ffi: ^1.0.0
  camera: any
  image_picker: ^0.6.3+4
  path_provider: ^2.0.6
  splashscreen: ^1.3.5
  shared_preferences: ^0.5.7
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800